name: findara
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
 
  flutter_local_notifications: ^17.2.4
  flutter_svg: ^2.0.10+1
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  percent_indicator: ^4.2.3
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"


flutter:


  uses-material-design: true


  assets:
    - images/
    - images/svg/welcome.svg
    - images/svg/tracking.svg
    - images/svg/notification.svg
    - images/svg/Following-bro.svg
    - images/svg/push.svg
    - assets/icons/chicken.svg
    - assets/icons/canard.svg
    - assets/icons/poule.svg
 


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_icons:
  android: true
  ios: true
  image_path: "images/logoFinale.jpg"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logoFin.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/logoFin.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/logoFin.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/logoFin.jpg"
